<?php
  include_once('simple_html_dom.php');
 
  $url = 'http://www.danseinfo.ch/';
 
  // get html from $url
  $html = file_get_html($url);
  
  // build rss feed
  Header("content-type: application/xml");
  echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
  echo "<!-- RSS generated by DanseInfo.ch " . date(DATE_RFC822) . "-->\n";
  echo "<rss version=\"2.0\" xmlns:atom=\"http://www.w3.org/2005/Atom\">\n";
  echo "  <channel>\n";
//  echo "    <atom:link href=\"" . $url . "rss.php\" rel=\"self\" type=\"application/rss+xml\" />\n";
	echo "   	<title>Danse Info News</title>\n";
	echo "	  <link>" . $url . "</link>\n";
	echo "	  <description>Agenda de la danse folk et trad en Suisse romande et environs.</description>\n";
	echo "	  <language>fr-fr</language>\n";
	echo "	  <copyright>Copyright 2011 DanseInfo.ch</copyright>\n";
	echo "	  <lastBuildDate>" . date("r") . "</lastBuildDate>\n";
	echo "	  <docs>http://backend.userland.com/rss</docs>\n";
	echo "	  <generator>BoumPower.ch</generator>\n";
	echo "	  <category>danse</category>\n";
//	echo "	  <managingEditor>dave@userland.com</managingEditor>\n";
	echo "	  <webMaster>webmaster@boumpower.ch (Olivier Baumgartner)</webMaster>\n";
	echo "	  <ttl>1440</ttl>\n";
   
  // build rss items
  foreach($html->find('div[class="article"]') as $e) {
    $h3 = $e->find('h3', 0);
    $body = $e->find('div[class="article-body"]', 0);
    if ((count($h3) == 1) && (count($body) == 1)) {
      $a = $h3->find('a', 0);
      if (count($a) == 1) {
        $pos = strrpos($a->href, "?jour=");
        if ($pos === false) { // note : 3 signes "="
          $date = getdate();
        } else {
          $date = strtotime(substr($a->href, $pos+6));
        }
        echo "      <item>\n";
//        echo "        <pubDate>" . date("r", $date) . "</pubDate>";
        echo "        <title>" . date("d.m.Y", $date) . " " . trim($a->plaintext) . "</title>\n";
        echo "        <link>" . $a->href . "</link>\n";
        echo "        <guid>" . $a->href . "</guid>\n";
        echo "        <description><![CDATA[" . $body->innertext . "]]></description>\n";
        echo "      </item>\n";
      }
    }
   }    
   
  echo "  </channel>\n";
  echo "</rss>\n";
    
  // Dump contents (without tags) from HTML
 // echo $html->plaintext;
?>
