<?php
  include_once('simple_html_dom.php');
  
// (c)2011 www.boumpower.ch  
 
  $url = 'http://www.danseinfo.ch/';
 
// build Google Agenda Button 
 function GoogleAgendaButton($text, $from_date, $to_date, $sprop, $details="", $location="") {
    $tag = "<a href=\"http://www.google.com/calendar/event?action=TEMPLATE" .
           "&text=" . rawurlencode($text) .
           "&dates=" . date("Ymd", $from_date) . "T" . date("His", $from_date) . "Z" .
                 "/" . date("Ymd", $to_date) . "T" . date("His", $to_date) . "Z" .
           "&sprop=website:" . rawurlencode($sprop) .
           "&details=" . rawurlencode($details) . 
           "&location=" . rawurlencode($location) . 
           "\" target=\"_blank\"><img src=\"http://www.google.com/calendar/images/ext/gc_button6_fr.gif\" border=0></a>";
    return $tag;
 }
 
  // get html from $url
  $html = file_get_html($url);
  
  // build rss feed
  Header("content-type: application/xml");
  echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
  echo "<!-- RSS generated by DanseInfo.ch " . date(DATE_RFC822) . "-->\n";
  echo "<rss version=\"2.0\" xmlns:atom=\"http://www.w3.org/2005/Atom\">\n";
  echo "  <channel>\n";
// uncomment following line and verify link  
//  echo "    <atom:link href=\"" . $url . "rss.php\" rel=\"self\" type=\"application/rss+xml\" />\n";
	echo "   	<title>Danse Info News</title>\n";
	echo "	  <link>" . $url . "</link>\n";
	echo "	  <description>Agenda de la danse folk et trad en Suisse romande et environs.</description>\n";
	echo "	  <language>fr-fr</language>\n";
	echo "	  <copyright>Copyright 2011 DanseInfo.ch</copyright>\n";
	echo "	  <lastBuildDate>" . date("r") . "</lastBuildDate>\n";
	echo "	  <docs>http://backend.userland.com/rss</docs>\n";
	echo "	  <generator>BoumPower.ch</generator>\n";
	echo "	  <category>danse</category>\n";
// uncomment following line with correct mail address	
//	echo "	  <managingEditor>dave@userland.com</managingEditor>\n";
// also change this one
	echo "	  <webMaster>webmaster@boumpower.ch (Olivier Baumgartner)</webMaster>\n";
	echo "	  <ttl>1440</ttl>\n";
   
  // build rss items from "article"  and "article-body"
  foreach($html->find('div[class="article"]') as $e) {
    $h3 = $e->find('h3', 0);
    $body = $e->find('div[class="article-body"]', 0);
    if ((count($h3) == 1) && (count($body) == 1)) {
      $a = $h3->find('a', 0);
      if (count($a) == 1) {
        // try to extract date from end of href found in "article"
        $pos = strrpos($a->href, "?jour=");
        if ($pos === false) { // note : 3 signes "="
          $date = getdate();
        } else {
          $date = strtotime(substr($a->href, $pos+6));
        }
        echo "      <item>\n";
// don't use pubDate, because it's future        
//        echo "        <pubDate>" . date("r", $date) . "</pubDate>";
        echo "        <title>" . date("d.m.Y", $date) . " " . trim($a->plaintext) . "</title>\n";
        echo "        <link>" . $a->href . "</link>\n";
        echo "        <guid>" . $a->href . "</guid>\n";
        echo "        <description><![CDATA[" . $body->innertext . 
                      GoogleAgendaButton(trim($a->plaintext), $date, $date, $url, $a->href) . "]]></description>\n";
        echo "      </item>\n";
      }
    }
   }    
   
  echo "  </channel>\n";
  echo "</rss>\n";
    
  // Dump contents (without tags) from HTML for debug
 // echo $html->plaintext;
?>
