// LTSetup messages in localised language
// (optional : if not present, internal English/German language is used)
// Copyright (c) 2001-2005 TM-CAD Engineering Torsten Moses
//
// DELETE THIS FILE IF ORIGINAL, BUILT-IN MESSAGES SHALL BE USED !!
// BUILT-IN LANGUAGES : GERMAN, ENGLISH

[MESSAGES]
IDS_INSTALLTITLE      = Installation de BpsAcad pour AutoCAD LT
IDS_UNINSTALLTITLE    = Suppression de BpsAcad pour AutoCAD LT
IDS_INSTALLBUTTON     = Installer
IDS_UNINSTALLBUTTON   = Supprimer
IDS_BUTTON_CANCEL     = Annuler
IDS_INSTALLSUCCESS    = BpsAcad pour AutoCAD LT a été installé avec succès sur votre ordinateur!
IDS_UNINSTALLSUCCESS  = BpsAcad pour AutoCAD LT a été supprimé de votre ordinateur!
IDS_ERR_LTNOTFOUND    = AutoCAD LT doit être installé avant de lancer LTSetup. S.V.P. installer une version supportée d'AutoCAD LT et relancer LTSetup.
IDS_ERR_BADCFG        = LTSetup ne peut pas modifier votre configuration à cause d'un fichier erroné. Vous devez créer une nouvelle configuration et relancer LTSetup.
IDS_ERR_NOBAK         = LTSetup ne peut pas sauvegarder votre fichier de configuration courante d'AutoCAD LT. Voulez-vous continuer ?
IDS_ERR_NODRV         = LTSetup nécessite au moins un traceur configuré dans AutoCAD LT. S.V.P. configurer un traceur dans AutoCAD LT et relancer LTSetup.
IDS_ERR_BADREG        = LTSetup ne peut pas modifier les paramètres AutoCAD LT du registre. Votre installation AutoCAD LT n'est peut-être pas supportée ou corrompue. Vous pouvez essayer de réinstaller AutoCAD LT, et relancer LTSetup.
IDS_ERR_BADDLL        = LTSetup ne trouve pas une DLL. Vérifier que tous les fichiers LTX sont dans le même répertoire que le programme LTSetup.
IDS_ERR_UNKNOWN       = Une erreur inconnue est survenue durant l'exécution de LTSetup. Cette erreur est certainement due à une erreur de flux dans LTSetup. S.V.P. contacter le support technique de LT-Extender à developer@LT-Extender.com.
IDS_ERR_RUNLTFIRST    = La version AutoCAD LT n'a jamais été lancée -|Certains paramètres du registre sont manquants, ils doivent être créé au premier lancement de LT.|S.V.P lancer AutoCAD LT et|relancer LTSetup.

IDS_PAGE_9798_MSG_1   = BpsAcad peut être installé avec un ou plusieurs fichier de configuration AutoCAD LT (*.cfg). Le fichier de configuration par défaut est aclt4.cfg (LT 97) ou aclt5.cfg (LT 98) localisé dans le répertoire principal d'AutoCAD LT.
IDS_PAGE_9798_MSG_2   = Les fichiers de configuration suivants ont été trouvés sur votre ordinateur. Sélectionner les configurations à modifier. Presser le bouton <Ajouter...> pour ajouter des fichiers de configuration.
IDS_PAGE_9798_MSG_3   = Sélectionner le(s) fichier(s) de configuration :
IDS_PAGE_9798_MSG_ADD = Ajouter...

IDS_PAGE_2000_MSG_1   = BpsAcad doit modifier des paramètres du registre.|Si vous avez plusieurs installation d'AutoCAD LT, vous pouvez spécifier une ou plusieurs installations existantes.
IDS_PAGE_2000_MSG_2   = Les installations suivantes d'AutoCAD LT ont été trouvées sur votre ordinateur. Sélectionner l'installation(s) à modifier.
IDS_PAGE_2000_MSG_3   = Sélectionner l'installation(s) AutoCAD LT :

