// LTSetup / LTUninst messages file
// Copyright (c) 2001-2003 TM-CAD Engineering Torsten Moses
//
// This file defines messages used by ManuSoft LTSetup.exe / LTUninst.exe
// if there are no appropriate messages built-in
//
// DELETE THIS FILE IF ORIGINAL, BUILT-IN MESSAGES SHALL BE USED !!
// BUILT-IN LANGUAGES : GERMAN, ENGLISH, FRENCH

[MESSAGES]
IDS_INSTALLTITLE      = Install <application> for AutoCAD LT
IDS_UNINSTALLTITLE    = Uninstall <application> for AutoCAD LT
IDS_INSTALLBUTTON     = Install
IDS_UNINSTALLBUTTON   = Uninstall
IDS_BUTTON_CANCEL     = Cancel
IDS_INSTALLSUCCESS    = <application> for AutoCAD LT has been successfully installed!
IDS_UNINSTALLSUCCESS  = <application> for AutoCAD LT has been successfully uninstalled!
IDS_ERR_LTNOTFOUND    = AutoCAD LT must be installed before running Setup for LT.|Please install a supported version of AutoCAD LT then try again.
IDS_ERR_BADCFG        = Setup could not modify your configuration due to unexpected file contents.|You may need to create a new configuration, then run setup again.
IDS_ERR_NOBAK         = Setup could not make a backup of your current AutoCAD LT configuration file.|Do you wish to continue anyway ?
IDS_ERR_NODRV         = Setup requires at least one output device configured in AutoCAD LT.|Please configure a plotter in AutoCAD LT, then run setup again.
IDS_ERR_BADREG        = Setup could not modify your AutoCAD LT registry settings.|Your AutoCAD LT installation may not be supported, or it may be corrupt.|You may need to reinstall AutoCAD LT, then run setup again.
IDS_ERR_BADDLL        = Setup could not find a DLL that it needs to continue.|Please make sure all LTX files are in the same folder|as the setup program.
IDS_ERR_UNKNOWN       = An unknown error has prevented setup from completing.|This error is most likely caused by a flaw in the setup program.|Please report the problem to ManuSoft technical support at|support@manusoft.com.
IDS_ERR_RUNLTFIRST    = The AutoCAD LT version from specified path has never run before -|some registry keys are missing, that will be created at first LT start.|Please start LT from the specified path, then|run LTSetup again to register with that LT version.

IDS_PAGE_9798_MSG_1   = <application> may be installed into one or more AutoCAD LT configuration (*.cfg) files. The default configuration file is aclt4.cfg (LT 97) or aclt5.cfg (LT 98) located in the main AutoCAD LT folder.
IDS_PAGE_9798_MSG_2   = The following configuration files were found on your system. Select the configurations to modify. Press the <Add> button to add additional configuration files.
IDS_PAGE_9798_MSG_3   = Select target configuration file(s):
IDS_PAGE_9798_MSG_ADD = Add...

IDS_PAGE_2000_MSG_1   = <application> setup must modify registry settings. If you have multiple AutoCAD LT 2000/2000i/2002/2004 installations, you may specify one or more of the existing installations.
IDS_PAGE_2000_MSG_2   = The following AutoCAD LT 2000/2000i/2002/2004 installations were found on your system. Select the installation(s) to modify.
IDS_PAGE_2000_MSG_3   = Select target AutoCAD LT installation(s) :

