// LTSetup / LTUninst messages file
// Copyright (c) 2001-2004 TM-CAD Engineering Torsten Moses
//
// This file defines messages used by ManuSoft LTSetup.exe / LTUninst.exe
// if there are no appropriate messages built-in
//
// DELETE THIS FILE IF ORIGINAL, BUILT-IN MESSAGES SHALL BE USED !!
// BUILT-IN LANGUAGES : GERMAN, ENGLISH, FRENCH

[MESSAGES]
IDS_INSTALLTITLE      = Installation <Applikation> für AutoCAD LT
IDS_UNINSTALLTITLE    = De-Installation <Applikation> für AutoCAD LT
IDS_INSTALLBUTTON     = Installieren
IDS_UNINSTALLBUTTON   = De-Installieren
IDS_BUTTON_CANCEL     = Abbruch
IDS_INSTALLSUCCESS    = <Applikation> für AutoCAD LT wurde erfolgreich installiert !
IDS_UNINSTALLSUCCESS  = <Applikation> für AutoCAD LT wurde erfolgreich deinstalliert !
IDS_ERR_LTNOTFOUND    = AutoCAD LT muss installiert sein, bevor dieses Setup für LT ausgeführt werden kann !|Bitte installieren Sie eine oder mehrere der unterstützten AutoCAD LT Versionen und führen|Sie dann dieses Setup erneut aus.
IDS_ERR_BADCFG        = Setup kann die Konfiguration nicht verwenden, da die Konfigurations-Datei|unbekannte Daten enthält. Erstellen Sie eine neue Konfigurations-Datei und führen dann dieses Setup erneut aus.
IDS_ERR_NOBAK         = Setup konnte keine Sicherheits-Kopie der aktuellen Konfigurations-Datei anlegen -|möchten Sie das Setup dennoch fortsetzen ?
IDS_ERR_NODRV         = Um Setup erfolgreich auszuführen, muss mindestens 1 Ausgabe-Gerät (Drucker/Plotter)|konfiguriert sein ! Bitte konfigurieren Sie einen Drucker/Plotter|und führen Sie dann Setup erneut aus.
IDS_ERR_BADREG        = Setup konnte die AutoCAD LT Registry nicht aktualisieren.|Möglicherweise wird Ihre AutoCAD LT Installation nicht unterstützt|oder die Registry-Daten sind beschädigt. Installieren Sie AutoCAD LT|ggf. erneut, und führen Sie dann Setup nochmals aus.
IDS_ERR_BADDLL        = Setup konnte eine benötigte DLL Datei nicht finden. Bitte stellen Sie sicher, daß alle LTX Dateien im gleichen Verzeichnis wie das Setup - Programm vorhanden sind.
IDS_ERR_UNKNOWN       = Ein nicht erkannter Fehler verhinderte, daß Setup erfolgreich ausgeführt werden konnte.|Dieser Fehler ist meistens durch das Setup - Programm selbst begründet.|Bitte schicken Sie einen Fehler-Bericht an den technischen Support von "ManuSoft" (support@manusoft.com).
IDS_ERR_RUNLTFIRST    = Die angegebene AutoCAD LT Version ist bisher noch nicht gestartet worden - |daher fehlen einige Registry-Einträge, welche LT beim ersten Start anlegt\n\nStarten Sie daher bitte die LT-Version im angegebenen Pfad,|und wiederholen Sie dann LTSetup.

IDS_PAGE_9798_MSG_1   = <Applikation> kann in eine oder mehrere  AutoCAD LT Konfigurationen (*.cfg) installiert werden. Die Standard - Konfigurationen sind "aclt4.cfg" (LT97) und "aclt5.cfg" (LT98). Die Dateien finden Sie normalerweise im AutoCAD LT Verzeichnis.
IDS_PAGE_9798_MSG_2   = Die folgenden Konfigurationen wurden gefunden - wählen Sie die zu nutzende(n) Konfiguration(en) aus; mit <Hinzufügen> können Sie weitere Konfigurationen hinzufügen.
IDS_PAGE_9798_MSG_3   = Wählen Sie die zu nutzende(n) Konfiguration(en):
IDS_PAGE_9798_MSG_ADD = Hinzufügen...

IDS_PAGE_2000_MSG_1   = <Applikation> Setup muss einige AutoCAD LT Registry - Einträge aktualisieren. Wenn Sie mehrere AutoCAD LT 2000/2000i/2002/2004 Installationen verwenden, können Sie eine oder mehrere Installationen auswählen.
IDS_PAGE_2000_MSG_2   = Die nachfolgend aufgeführten AutoCAD LT 2000/2000i/2002/2004 Installationen wurden gefunden -- bitte wählen Sie die gewünschten AutoCAD LT Installation(en) aus:
IDS_PAGE_2000_MSG_3   = Wählen Sie die AutoCAD LT Installationen :

